apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-database-user
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: grafana-database-user
    creationPolicy: Owner
  data:
  - secretKey: dbpwd
    remoteRef:
      key: demo/dev/db/grafana
      property: database.password
  - secretKey: dbuser
    remoteRef: 
      key: demo/dev/db/grafana 
      property: database.user
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-exporter-user
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: mongodb-exporter-user
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: demo/dev/db/mongodb-exporter
      property: password
  - secretKey: username
    remoteRef:
      key: demo/dev/db/mongodb-exporter 
      property: username
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-exporter-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: mysql-exporter-config
    creationPolicy: Owner
  data:
  - secretKey: my.cnf
    remoteRef:
      key: demo/dev/db/mysql-exporter
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-exporter-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: postgres-exporter-config
    creationPolicy: Owner
  data:
  - secretKey: postgres_exporter.yml
    remoteRef:
      key: demo/dev/db/postgres-exporter