apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psmdb-admin
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: psmdb-admin
    creationPolicy: Owner
  data:
    - secretKey: example-org_mon
      remoteRef:
        key: demo/dev/db/admin # aws secret manager key name
        property: example-org_mon
    - secretKey: example-org_bak
      remoteRef:
        key: demo/dev/db/admin
        property: example-org_bak
    - secretKey: example-org_admin
      remoteRef:
        key: demo/dev/db/admin
        property: example-org_admin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psmdb-user
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: psmdb-user
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_BACKUP_USER
      remoteRef:
        key: demo/dev/db/psmdb # aws secret manager key name
        property: MONGODB_BACKUP_USER
    - secretKey: MONGODB_BACKUP_PASSWORD
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_BACKUP_PASSWORD
    - secretKey: MONGODB_DATABASE_ADMIN_USER
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_DATABASE_ADMIN_USER
    - secretKey: MONGODB_DATABASE_ADMIN_PASSWORD
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_DATABASE_ADMIN_PASSWORD
    - secretKey: MONGODB_CLUSTER_ADMIN_USER
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_CLUSTER_ADMIN_USER
    - secretKey: MONGODB_CLUSTER_ADMIN_PASSWORD
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_CLUSTER_ADMIN_PASSWORD
    - secretKey: MONGODB_USER_ADMIN_USER
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_USER_ADMIN_USER
    - secretKey: MONGODB_USER_ADMIN_PASSWORD
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_USER_ADMIN_PASSWORD
    - secretKey: MONGODB_CLUSTER_MONITOR_USER
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_CLUSTER_MONITOR_USER
    - secretKey: MONGODB_CLUSTER_MONITOR_PASSWORD
      remoteRef:
        key: demo/dev/db/psmdb
        property: MONGODB_CLUSTER_MONITOR_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psmdb-ssl
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: psmdb-ssl
    template:
      type: kubernetes.io/tls
      data:
        ca.crt: "{{ .CA }}"
        tls.crt: "{{ .TLS }}"
        tls.key: "{{ .KEY }}"
    creationPolicy: Owner
  data:
    - secretKey: CA
      remoteRef:
        key: demo/dev/db/psmdb-ssl/ca
    - secretKey: TLS
      remoteRef:
        key: demo/dev/db/psmdb-ssl/tls
    - secretKey: KEY
      remoteRef:
        key: demo/dev/db/psmdb-ssl/key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psmdb-ssl-internal
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    name: psmdb-ssl-internal
    template:
      type: kubernetes.io/tls
      data:
        ca.crt: "{{ .CA }}"
        tls.crt: "{{ .TLS }}"
        tls.key: "{{ .KEY }}"
    creationPolicy: Owner
  data:
    - secretKey: CA
      remoteRef:
        key: demo/dev/db/psmdb-ssl-internal/ca
    - secretKey: TLS
      remoteRef:
        key: demo/dev/db/psmdb-ssl-internal/tls
    - secretKey: KEY
      remoteRef:
        key: demo/dev/db/psmdb-ssl-internal/key
