apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        generated: karpenter
        service: mongodb
        team: devops
    spec:
      kubelet:
        systemReserved:
          cpu: 100m
          memory: 100Mi
      nodeClassRef:
        name: mongodb
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - r
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: 
            - "r6g"
            - "r7g"
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - "4"
            - "8"
            - "16"
            - "32"
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
            - nitro
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - "5"
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-northeast-2a
            - ap-northeast-2c
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
            - arm64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - effect: NoSchedule
          key: MongoDBOnly
          value: "true"
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  weight: 100
