apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: db
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
  role: karpenter-security-prod-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: security-prod-eks
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: security-prod-eks
  tags:
    Env: security-prod
    KarpenterNodePoolName: db
    Group: db
    NodeType: ops_db_prod_ec2
    Team: ops
    csmSecurity: "true"
    intent: apps
    karpenter.sh/discovery: security-prod-eks
