apiVersion: v1
kind: Namespace
metadata:
  name: cve-monitor
  labels:
    name: cve-monitor
    purpose: cve-monitoring
    team: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cve-monitor
  namespace: cve-monitor
  labels:
    app: cve-monitor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cve-monitor-config
  namespace: cve-monitor
data:
  LOG_LEVEL: "INFO"
  TIMEZONE: "Asia/Seoul"
  SLACK_CHANNEL: "#엔지니어링_기술뉴스"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cve-notification-monitor
  namespace: cve-monitor
  annotations:
    argocd-image-updater.argoproj.io/image-list: scanner=123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/security-cron
    argocd-image-updater.argoproj.io/scanner.update-strategy: latest
  labels:
    app: cve-monitor
    component: cve-alert
spec:
  schedule: "0 9 * * 1-5"  # 평일(월-금) 오전 9시 (KST)
  timeZone: "Asia/Seoul"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: cve-monitor
            component: cve-alert
        spec:
          serviceAccountName: cve-monitor
          restartPolicy: OnFailure
          containers:
          - name: cve-notifier
            image: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/security-cron:latest
            imagePullPolicy: Always
            command: ["/bin/bash", "-c"]
            args:
              - |
                echo "Starting CVE monitoring at $(date)"
                python cve-notif.py
                echo "CVE monitoring completed at $(date)"
            env:
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: cve-slack-webhook
                  key: SLACK_WEBHOOK
            - name: VULNERS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: VULNERS_API_KEY
                  optional: true
            - name: NVD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: NVD_API_KEY
                  optional: true
            envFrom:
            - configMapRef:
                name: cve-monitor-config
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          nodeSelector:
            service: "common-addons"
          tolerations:
          - key: "CommonAddonsOnly"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
