apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  data:
    - secretKey: api-key
      remoteRef:
        key: demo/prod/devops
        property: DATADOG_API_KEY
    - secretKey: app-key
      remoteRef:
        key: demo/prod/devops
        property: DATADOG_APP_KEY
    - secretKey: token
      remoteRef:
        key: demo/prod/devops
        property: DATADOG_TOKEN
    - secretKey: synthetics-check-runner.json
      remoteRef:
        key: demo/prod/devops
        property: synthetics-check-runner-json
    - secretKey: mongodb-datadog-password
      remoteRef:
        key: demo/prod/devops
        property: DATADOG_MONGO_USER_PASSWORD
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
