# This file is directly copied from the following GitHub repository with a little modificiation.
# https://github.com/chatwork/kube-schedule-scaler
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-schedule-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-schedule-scaler
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-schedule-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-schedule-scaler
subjects:
  - kind: ServiceAccount
    name: kube-schedule-scaler
    namespace: kube-schedule-scaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-schedule-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-schedule-scaler
  template:
    metadata:
      labels:
        application: kube-schedule-scaler
    spec:
      serviceAccountName: kube-schedule-scaler
      priorityClassName: common-addons
      containers:
        - name: kube-schedule-scaler
          image: chatwork/kube-schedule-scaler:edge
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 500Mi
            requests:
              cpu: 800m
              memory: 500Mi
      nodeSelector:
        service: common-addons
      tolerations:
        - effect: NoSchedule
          key: CommonAddonsOnly
          operator: Equal
          value: "true"
