service: data-mlops-bs-legacy-i2v-ranking
owner:
  - name: 조영훈
    email: younghun.jo@iexample-org.com
slack_channels:
  - 모니터링_데이터_운영
monitors:
  - monitor_type: error_log
    threshold: 5
  - monitor_type: api_latency
    threshold: 10
    duration: 700
  - monitor_type: alb_5xx
    threshold: 5
    loadbalancer: bs-legacy-i2v-ranking-prod
  - monitor_type: alb_target_5xx
    threshold: 5
    loadbalancer: bs-legacy-i2v-ranking-prod
  - monitor_type: error_tracking_trace
    threshold: 5
synthetics:
  - name: data-mlops-bs-legacy-i2v-ranking-prod가 다운되었습니다.
    type: api
    subtype: http
    status: "live"
    locations: ["pl:devops-private-location-dc242ec68f6544a123e787d5345b2e06"]
    request_definition:
      method: GET
      url: https://data-mlops-bs-legacy-i2v-ranking.data.prod.iexample-org.com/health-check
    assertions:
      - type: statusCode
        operator: is
        target: 200
      - type: responseTime
        operator: lessThan
        target: 3000
    options_list:
      tick_every: 60
      retry:
        count: 3
        interval: 1000
      monitor_options:
        renotify_interval: 10
