# syntax=docker/dockerfile:1.7-labs
# Base Build Stage
FROM node:18.16.0-alpine AS base-builder
RUN apk --no-cache add curl jq && npm install -g npm@9.3.1 && npm install -g pm2

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG ENCRYPT_KEY

RUN apk add --no-cache \
    chromium \
    chromium-chromedriver \
    nss \
    ca-certificates \
    libgcc \
    libstdc++

WORKDIR /home/alwayz-cron

COPY createEnv.js .
COPY package.json package-lock.json ./
RUN npm pkg delete scripts.prepare && npm ci --omit=dev

COPY --exclude=package* ./ ./

ARG IMAGE_TAG
ENV NODE_ENV=dev
ENV DD_VERSION=${IMAGE_TAG}

RUN response=$(curl -s https://config.dev.example.com/env/alwayz-cron/dev) && \
    data=$(echo $response | jq -r '.data') && \
    node createEnv.js "$data" "$ENCRYPT_KEY"

RUN if [ ! -f .env ]; then echo ".env 파일이 없습니다. 도커 빌드를 중지합니다." && exit 1; fi

ENTRYPOINT ["node", "main.js"]
