FROM python:3.10-slim AS builder

ENV WORKDIR=/app/

WORKDIR ${WORKDIR}

COPY Pipfile Pipfile.lock ${WORKDIR}

RUN pip install pipenv --no-cache-dir && \
    pipenv install --system --ignore-pipfile && \
    pip uninstall -y pipenv virtualenv-clone virtualenv


# Config Build Stage
FROM node:18.16.0-alpine AS config-builder

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG GIT_PERSONAL_ACCESS_TOKEN

RUN apk update && apk --no-cache add git

WORKDIR /home/demo-config
ARG CACHEBUST=1
RUN git clone https://ilevit-dev:${GIT_PERSONAL_ACCESS_TOKEN}@github.com/wetripod/demo-config .
RUN npm install && npm run build


FROM python:3.10-slim AS deployer

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /usr/lib /usr/lib
COPY --from=config-builder /home/demo-config/output/demo-python-cron/.env.dev /app/.env.dev
COPY --from=builder /app /app

COPY . .

ENTRYPOINT ["python3", "main.py"]
CMD ["--name", "default_name", "--files", "default_files"]