apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: demo-bff
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: 82199d79-c2a8-450b-8f8b-a3176eb738b9
  role: karpenter-demo-prod-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: demo-prod-eks
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: demo-prod-eks
  tags:
    Env: demo-prod
    Group: demo-bff
    KarpenterNodePoolName: demo-bff
    NodeType: home-and-deal_demo-bff_prod_ec2
    Team: home-and-deal
    csmSecurity: "true"
    karpenter.sh/discovery: demo-prod-eks
